### PR TITLE
Convert to js

### PR DESCRIPTION
**Pull request by trotzig**
The time has come for happo version 3.0. The last few months have been very rewarding, and sometimes frustrating. But we're finally at a place where the javascript-rewritten, performance-improved, bad-ass happo 3 is ready.

### CODE REVIEW

**Comment by lencioni** [comment]
:shipit:

**Comment by lencioni** [comment]
Looks like you've got some spec failures tho

**Comment by trotzig** [comment]
Yeah, silly mistake. Fixed now (I hope).

**Comment by trotzig** [comment]
All green. Here we go! :shipit:

**Pull request merged**
